// DO NOT EDIT: Code generated by matcha from later.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree() -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "<script type=\"module\" src=\"/client.min.mjs\"></script>
<body>
    <div id=\"client\"></div>
</body>
")

    tree
}

pub fn render() -> String {
    string_tree.to_string(render_tree())
}

