// DO NOT EDIT: Code generated by matcha from list.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree() -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "<script src=\"/client.mjs\"></script>
<div id=\"client\" hx-on:htmx:trigger=\"document.lustre.list_main()\" hx-trigger=\"intersect once\"></div>
")

    tree
}

pub fn render() -> String {
    string_tree.to_string(render_tree())
}

