// DO NOT EDIT: Code generated by matcha from list.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree() -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "<script src=\"/test.mjs\"></script>
<client-app></client-app>
<div id=\"client\"></div>
")

    tree
}

pub fn render() -> String {
    string_tree.to_string(render_tree())
}

