// DO NOT EDIT: Code generated by matcha from profile.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree(user_id user_id: String) -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "
<h1>hello ")
    let tree = string_tree.append(tree, user_id)
    let tree = string_tree.append(tree, "</h1>
")

    tree
}

pub fn render(user_id user_id: String) -> String {
    string_tree.to_string(render_tree(user_id: user_id))
}

