// DO NOT EDIT: Code generated by matcha from recipes.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree() -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "<h1>Coming Soon!</h1>
")

    tree
}

pub fn render() -> String {
    string_tree.to_string(render_tree())
}

